 export const countries = [
        { value: "AF", label: "Afghanistan", flag: "🇦🇫", continent: "Asia" },
        { value: "AL", label: "Albania", flag: "🇦🇱", continent: "Europe" },
        { value: "DZ", label: "Algeria", flag: "🇩🇿", continent: "Africa" },
        { value: "AD", label: "Andorra", flag: "🇦🇩", continent: "Europe" },
        { value: "AO", label: "Angola", flag: "🇦🇴", continent: "Africa" },
        { value: "AG", label: "Antigua and Barbuda", flag: "🇦🇬", continent: "America" },
        { value: "AR", label: "Argentina", flag: "🇦🇷", continent: "America" },
        { value: "AM", label: "Armenia", flag: "🇦🇲", continent: "Asia" },
        { value: "AU", label: "Australia", flag: "🇦🇺", continent: "Oceania" },
        { value: "AT", label: "Austria", flag: "🇦🇹", continent: "Europe" },
        { value: "AZ", label: "Azerbaijan", flag: "🇦🇿", continent: "Asia" },
        { value: "BS", label: "Bahamas", flag: "🇧🇸", continent: "America" },
        { value: "BH", label: "Bahrain", flag: "🇧🇭", continent: "Asia" },
        { value: "BD", label: "Bangladesh", flag: "🇧🇩", continent: "Asia" },
        { value: "BB", label: "Barbados", flag: "🇧🇧", continent: "America" },
        { value: "BY", label: "Belarus", flag: "🇧🇾", continent: "Europe" },
        { value: "BE", label: "Belgium", flag: "🇧🇪", continent: "Europe" },
        { value: "BZ", label: "Belize", flag: "🇧🇿", continent: "America" },
        { value: "BJ", label: "Benin", flag: "🇧🇯", continent: "Africa" },
        { value: "BT", label: "Bhutan", flag: "🇧🇹", continent: "Asia" },
        { value: "BO", label: "Bolivia", flag: "🇧🇴", continent: "America" },
        { value: "BA", label: "Bosnia and Herzegovina", flag: "🇧🇦", continent: "Europe" },
        { value: "BW", label: "Botswana", flag: "🇧🇼", continent: "Africa" },
        { value: "BR", label: "Brazil", flag: "🇧🇷", continent: "America" },
        { value: "BN", label: "Brunei", flag: "🇧🇳", continent: "Asia" },
        { value: "BG", label: "Bulgaria", flag: "🇧🇬", continent: "Europe" },
        { value: "BF", label: "Burkina Faso", flag: "🇧🇫", continent: "Africa" },
        { value: "BI", label: "Burundi", flag: "🇧🇮", continent: "Africa" },
        { value: "CV", label: "Cabo Verde", flag: "🇨🇻", continent: "Africa" },
        { value: "KH", label: "Cambodia", flag: "🇰🇭", continent: "Asia" },
        { value: "CM", label: "Cameroon", flag: "🇨🇲", continent: "Africa" },
        { value: "CA", label: "Canada", flag: "🇨🇦", continent: "America" },
        { value: "CF", label: "Central African Republic", flag: "🇨🇫", continent: "Africa" },
        { value: "TD", label: "Chad", flag: "🇹🇩", continent: "Africa" },
        { value: "CL", label: "Chile", flag: "🇨🇱", continent: "America" },
        { value: "CN", label: "China", flag: "🇨🇳", continent: "Asia" },
        { value: "CO", label: "Colombia", flag: "🇨🇴", continent: "America" },
        { value: "KM", label: "Comoros", flag: "🇰🇲", continent: "Africa" },
        { value: "CG", label: "Congo", flag: "🇨🇬", continent: "Africa" },
        { value: "CD", label: "DR Congo", flag: "🇨🇩", continent: "Africa" },
        { value: "CR", label: "Costa Rica", flag: "🇨🇷", continent: "America" },
        { value: "HR", label: "Croatia", flag: "🇭🇷", continent: "Europe" },
        { value: "CU", label: "Cuba", flag: "🇨🇺", continent: "America" },
        { value: "CY", label: "Cyprus", flag: "🇨🇾", continent: "Asia" },
        { value: "CZ", label: "Czechia", flag: "🇨🇿", continent: "Europe" },
        { value: "DK", label: "Denmark", flag: "🇩🇰", continent: "Europe" },
        { value: "DJ", label: "Djibouti", flag: "🇩🇯", continent: "Africa" },
        { value: "DM", label: "Dominica", flag: "🇩🇲", continent: "America" },
        { value: "DO", label: "Dominican Republic", flag: "🇩🇴", continent: "America" },
        { value: "EC", label: "Ecuador", flag: "🇪🇨", continent: "America" },
        { value: "EG", label: "Egypt", flag: "🇪🇬", continent: "Africa" },
        { value: "SV", label: "El Salvador", flag: "🇸🇻", continent: "America" },
        { value: "GQ", label: "Equatorial Guinea", flag: "🇬🇶", continent: "Africa" },
        { value: "ER", label: "Eritrea", flag: "🇪🇷", continent: "Africa" },
        { value: "EE", label: "Estonia", flag: "🇪🇪", continent: "Europe" },
        { value: "SZ", label: "Eswatini", flag: "🇸🇿", continent: "Africa" },
        { value: "ET", label: "Ethiopia", flag: "🇪🇹", continent: "Africa" },
        { value: "FJ", label: "Fiji", flag: "🇫🇯", continent: "Oceania" },
        { value: "FI", label: "Finland", flag: "🇫🇮", continent: "Europe" },
        { value: "FR", label: "France", flag: "🇫🇷", continent: "Europe" },
        { value: "GA", label: "Gabon", flag: "🇬🇦", continent: "Africa" },
        { value: "GM", label: "Gambia", flag: "🇬🇲", continent: "Africa" },
        { value: "GE", label: "Georgia", flag: "🇬🇪", continent: "Asia" },
        { value: "DE", label: "Germany", flag: "🇩🇪", continent: "Europe" },
        { value: "GH", label: "Ghana", flag: "🇬🇭", continent: "Africa" },
        { value: "GR", label: "Greece", flag: "🇬🇷", continent: "Europe" },
        { value: "GD", label: "Grenada", flag: "🇬🇩", continent: "America" },
        { value: "GT", label: "Guatemala", flag: "🇬🇹", continent: "America" },
        { value: "GN", label: "Guinea", flag: "🇬🇳", continent: "Africa" },
        { value: "GW", label: "Guinea-Bissau", flag: "🇬🇼", continent: "Africa" },
        { value: "GY", label: "Guyana", flag: "🇬🇾", continent: "America" },
        { value: "HT", label: "Haiti", flag: "🇭🇹", continent: "America" },
        { value: "HN", label: "Honduras", flag: "🇭🇳", continent: "America" },
        { value: "HU", label: "Hungary", flag: "🇭🇺", continent: "Europe" },
        { value: "IS", label: "Iceland", flag: "🇮🇸", continent: "Europe" },
        { value: "IN", label: "India", flag: "🇮🇳", continent: "Asia" },
        { value: "ID", label: "Indonesia", flag: "🇮🇩", continent: "Asia" },
        { value: "IR", label: "Iran", flag: "🇮🇷", continent: "Asia" },
        { value: "IQ", label: "Iraq", flag: "🇮🇶", continent: "Asia" },
        { value: "IE", label: "Ireland", flag: "🇮🇪", continent: "Europe" },
        { value: "IL", label: "Israel", flag: "🇮🇱", continent: "Asia" },
        { value: "IT", label: "Italy", flag: "🇮🇹", continent: "Europe" },
        { value: "JM", label: "Jamaica", flag: "🇯🇲", continent: "America" },
        { value: "JP", label: "Japan", flag: "🇯🇵", continent: "Asia" },
        { value: "JO", label: "Jordan", flag: "🇯🇴", continent: "Asia" },
        { value: "KZ", label: "Kazakhstan", flag: "🇰🇿", continent: "Asia" },
        { value: "KE", label: "Kenya", flag: "🇰🇪", continent: "Africa" },
        { value: "KI", label: "Kiribati", flag: "🇰🇮", continent: "Oceania" },
        { value: "KP", label: "North Korea", flag: "🇰🇵", continent: "Asia" },
        { value: "KR", label: "South Korea", flag: "🇰🇷", continent: "Asia" },
        { value: "KW", label: "Kuwait", flag: "🇰🇼", continent: "Asia" },
        { value: "KG", label: "Kyrgyzstan", flag: "🇰🇬", continent: "Asia" },
        { value: "LA", label: "Laos", flag: "🇱🇦", continent: "Asia" },
        { value: "LV", label: "Latvia", flag: "🇱🇻", continent: "Europe" },
        { value: "LB", label: "Lebanon", flag: "🇱🇧", continent: "Asia" },
        { value: "LS", label: "Lesotho", flag: "🇱🇸", continent: "Africa" },
        { value: "LR", label: "Liberia", flag: "🇱🇷", continent: "Africa" },
        { value: "LY", label: "Libya", flag: "🇱🇾", continent: "Africa" },
        { value: "LI", label: "Liechtenstein", flag: "🇱🇮", continent: "Europe" },
        { value: "LT", label: "Lithuania", flag: "🇱🇹", continent: "Europe" },
        { value: "LU", label: "Luxembourg", flag: "🇱🇺", continent: "Europe" },
        { value: "MG", label: "Madagascar", flag: "🇲🇬", continent: "Africa" },
        { value: "MW", label: "Malawi", flag: "🇲🇼", continent: "Africa" },
        { value: "MY", label: "Malaysia", flag: "🇲🇾", continent: "Asia" },
        { value: "MV", label: "Maldives", flag: "🇲🇻", continent: "Asia" },
        { value: "ML", label: "Mali", flag: "🇲🇱", continent: "Africa" },
        { value: "MT", label: "Malta", flag: "🇲🇹", continent: "Europe" },
        { value: "MH", label: "Marshall Islands", flag: "🇲🇭", continent: "Oceania" },
        { value: "MR", label: "Mauritania", flag: "🇲🇷", continent: "Africa" },
        { value: "MU", label: "Mauritius", flag: "🇲🇺", continent: "Africa" },
        { value: "MX", label: "Mexico", flag: "🇲🇽", continent: "America" },
        { value: "FM", label: "Micronesia", flag: "🇫🇲", continent: "Oceania" },
        { value: "MD", label: "Moldova", flag: "🇲🇩", continent: "Europe" },
        { value: "MC", label: "Monaco", flag: "🇲🇨", continent: "Europe" },
        { value: "MN", label: "Mongolia", flag: "🇲🇳", continent: "Asia" },
        { value: "ME", label: "Montenegro", flag: "🇲🇪", continent: "Europe" },
        { value: "MA", label: "Morocco", flag: "🇲🇦", continent: "Africa" },
        { value: "MZ", label: "Mozambique", flag: "🇲🇿", continent: "Africa" },
        { value: "MM", label: "Myanmar", flag: "🇲🇲", continent: "Asia" },
        { value: "NA", label: "Namibia", flag: "🇳🇦", continent: "Africa" },
        { value: "NR", label: "Nauru", flag: "🇳🇷", continent: "Oceania" },
        { value: "NP", label: "Nepal", flag: "🇳🇵", continent: "Asia" },
        { value: "NL", label: "Netherlands", flag: "🇳🇱", continent: "Europe" },
        { value: "NZ", label: "New Zealand", flag: "🇳🇿", continent: "Oceania" },
        { value: "NI", label: "Nicaragua", flag: "🇳🇮", continent: "America" },
        { value: "NE", label: "Niger", flag: "🇳🇪", continent: "Africa" },
        { value: "NG", label: "Nigeria", flag: "🇳🇬", continent: "Africa" },
        { value: "NO", label: "Norway", flag: "🇳🇴", continent: "Europe" },
        { value: "OM", label: "Oman", flag: "🇴🇲", continent: "Asia" },
        { value: "PK", label: "Pakistan", flag: "🇵🇰", continent: "Asia" },
        { value: "PW", label: "Palau", flag: "🇵🇼", continent: "Oceania" },
        { value: "PA", label: "Panama", flag: "🇵🇦", continent: "America" },
        { value: "PG", label: "Papua New Guinea", flag: "🇵🇬", continent: "Oceania" },
        { value: "PY", label: "Paraguay", flag: "🇵🇾", continent: "America" },
        { value: "PE", label: "Peru", flag: "🇵🇪", continent: "America" },
        { value: "PH", label: "Philippines", flag: "🇵🇭", continent: "Asia" },
        { value: "PL", label: "Poland", flag: "🇵🇱", continent: "Europe" },
        { value: "PT", label: "Portugal", flag: "🇵🇹", continent: "Europe" },
        { value: "QA", label: "Qatar", flag: "🇶🇦", continent: "Asia" },
        { value: "RO", label: "Romania", flag: "🇷🇴", continent: "Europe" },
        { value: "RU", label: "Russia", flag: "🇷🇺", continent: "Europe" },
        { value: "RW", label: "Rwanda", flag: "🇷🇼", continent: "Africa" },
        { value: "KN", label: "Saint Kitts and Nevis", flag: "🇰🇳", continent: "America" },
        { value: "LC", label: "Saint Lucia", flag: "🇱🇨", continent: "America" },
        { value: "VC", label: "Saint Vincent and the Grenadines", flag: "🇻🇨", continent: "America" },
        { value: "WS", label: "Samoa", flag: "🇼🇸", continent: "Oceania" },
        { value: "SM", label: "San Marino", flag: "🇸🇲", continent: "Europe" },
        { value: "ST", label: "Sao Tome and Principe", flag: "🇸🇹", continent: "Africa" },
        { value: "SA", label: "Saudi Arabia", flag: "🇸🇦", continent: "Asia" },
        { value: "SN", label: "Senegal", flag: "🇸🇳", continent: "Africa" },
        { value: "RS", label: "Serbia", flag: "🇷🇸", continent: "Europe" },
        { value: "SC", label: "Seychelles", flag: "🇸🇨", continent: "Africa" },
        { value: "SL", label: "Sierra Leone", flag: "🇸🇱", continent: "Africa" },
        { value: "SG", label: "Singapore", flag: "🇸🇬", continent: "Asia" },
        { value: "SK", label: "Slovakia", flag: "🇸🇰", continent: "Europe" },
        { value: "SI", label: "Slovenia", flag: "🇸🇮", continent: "Europe" },
        { value: "SB", label: "Solomon Islands", flag: "🇸🇧", continent: "Oceania" },
        { value: "SO", label: "Somalia", flag: "🇸🇴", continent: "Africa" },
        { value: "ZA", label: "South Africa", flag: "🇿🇦", continent: "Africa" },
        { value: "SS", label: "South Sudan", flag: "🇸🇸", continent: "Africa" },
        { value: "ES", label: "Spain", flag: "🇪🇸", continent: "Europe" },
        { value: "LK", label: "Sri Lanka", flag: "🇱🇰", continent: "Asia" },
        { value: "SD", label: "Sudan", flag: "🇸🇩", continent: "Africa" },
        { value: "SR", label: "Suriname", flag: "🇸🇷", continent: "America" },
        { value: "SE", label: "Sweden", flag: "🇸🇪", continent: "Europe" },
        { value: "CH", label: "Switzerland", flag: "🇨🇭", continent: "Europe" },
        { value: "SY", label: "Syria", flag: "🇸🇾", continent: "Asia" },
        { value: "TJ", label: "Tajikistan", flag: "🇹🇯", continent: "Asia" },
        { value: "TZ", label: "Tanzania", flag: "🇹🇿", continent: "Africa" },
        { value: "TH", label: "Thailand", flag: "🇹🇭", continent: "Asia" },
        { value: "TL", label: "Timor-Leste", flag: "🇹🇱", continent: "Asia" },
        { value: "TG", label: "Togo", flag: "🇹🇬", continent: "Africa" },
        { value: "TO", label: "Tonga", flag: "🇹🇴", continent: "Oceania" },
        { value: "TT", label: "Trinidad and Tobago", flag: "🇹🇹", continent: "America" },
        { value: "TN", label: "Tunisia", flag: "🇹🇳", continent: "Africa" },
        { value: "TR", label: "Turkey", flag: "🇹🇷", continent: "Asia" },
        { value: "TM", label: "Turkmenistan", flag: "🇹🇲", continent: "Asia" },
        { value: "TV", label: "Tuvalu", flag: "🇹🇻", continent: "Oceania" },
        { value: "UG", label: "Uganda", flag: "🇺🇬", continent: "Africa" },
        { value: "UA", label: "Ukraine", flag: "🇺🇦", continent: "Europe" },
        { value: "AE", label: "United Arab Emirates", flag: "🇦🇪", continent: "Asia" },
        { value: "GB", label: "United Kingdom", flag: "🇬🇧", continent: "Europe" },
        { value: "US", label: "United States", flag: "🇺🇸", continent: "America" },
        { value: "UY", label: "Uruguay", flag: "🇺🇾", continent: "America" },
        { value: "UZ", label: "Uzbekistan", flag: "🇺🇿", continent: "Asia" },
        { value: "VU", label: "Vanuatu", flag: "🇻🇺", continent: "Oceania" },
        { value: "VE", label: "Venezuela", flag: "🇻🇪", continent: "America" },
        { value: "VN", label: "Vietnam", flag: "🇻🇳", continent: "Asia" },
        { value: "YE", label: "Yemen", flag: "🇾🇪", continent: "Asia" },
        { value: "ZM", label: "Zambia", flag: "🇿🇲", continent: "Africa" },
        { value: "ZW", label: "Zimbabwe", flag: "🇿🇼", continent: "Africa" }
    ]